import { Person } from './person';
import { getDaysLeft } from '../shared-module/week-days/week';

export const PEOPLE: Person[] = [
  {
    name: 'Piotr',
    skill: 'ASC',
    week: { mon: false, tue: true, wed: false, thu: true, fri: true },
    comments: 'DnA',
    daysLeft: getDaysLeft({
      mon: false,
      tue: true,
      wed: false,
      thu: true,
      fri: true,
    }),
    tags: [{ type: 'ind', value: 'FIG' }],
    availDate: new Date(),
    pdm: 'Livia Schneider',
  },
  {
    name: 'Mark',
    skill: 'EM',
    week: { mon: true, tue: true, wed: true, thu: true, fri: true },
    comments: "Doctor's visit on Fri",
    daysLeft: getDaysLeft({
      mon: true,
      tue: true,
      wed: true,
      thu: true,
      fri: true,
    }),
    tags: [{ type: 'fun', value: 'DnA' }],
    availDate: new Date(),
    pdm: 'Livia Schneider',
  },
  {
    name: 'Todd',
    skill: 'EM',
    week: { mon: true, tue: true, wed: true, thu: true, fri: false },
    comments: "Doctor's visit on Fri",
    daysLeft: getDaysLeft({
      mon: true,
      tue: true,
      wed: true,
      thu: true,
      fri: false,
    }),
    tags: [],
    availDate: new Date(Date.parse('28-Dec-2021')),
    pdm: 'Sabrina Reck',
  },
  {
    name: 'Tom',
    skill: 'BA',
    week: { mon: true, tue: true, wed: true, thu: true, fri: true },
    daysLeft: getDaysLeft({
      mon: true,
      tue: true,
      wed: true,
      thu: true,
      fri: true,
    }),
    tags: [],
    availDate: new Date(),
    pdm: 'Denada Heqimi',
  },
  {
    name: 'Tom',
    skill: 'EM',
    week: { mon: false, tue: false, wed: false, thu: false, fri: false },
    daysLeft: getDaysLeft({
      mon: false,
      tue: false,
      wed: false,
      thu: false,
      fri: false,
    }),
    tags: [],
    availDate: new Date(Date.parse('03-Jan-2022')),
    pdm: 'Sabrina Reck',
  },
  {
    name: 'Barbie',
    skill: 'BA',
    week: { mon: false, tue: false, wed: false, thu: false, fri: true },
    daysLeft: getDaysLeft({
      mon: false,
      tue: false,
      wed: false,
      thu: false,
      fri: true,
    }),
    tags: [],
    availDate: new Date(Date.parse('26-Dec-2021')),
    pdm: 'Piotr Ferensztajn',
  },
];
